apiVersion: v1 
kind: Service
metadata:
  name: jenkins 
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
  - name: jenkins 
    port: 80 
    targetPort: 8080
  selector:
    app: jenkins 
