apiVersion: v1 
kind: Service
metadata:
  name: jupyterhub-full-cpu
  labels:
    app: jupyterhub-full-cpu
#    dns: route53
#  annotations:
#    domainName: "jupyter.your.domain.com"
spec:
  type: LoadBalancer
  ports:
  - name: jupyterhub-full-cpu
    port: 80 
    targetPort: 8754
  - name: jupyterhub-api-proxy
    port: 81
    targetPort: 8755
  - name: tensorboard
    port: 6006
    targetPort: 6006
  selector:
    app: jupyterhub-full-cpu
