apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apachespark-worker-2-1-0
  labels:
    app: apachespark-worker-2-1-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apachespark-worker-2-1-0
  template:
    metadata:
      labels:
        app: apachespark-worker-2-1-0
    spec:
      containers:
      - name: apachespark-worker-2-1-0
        image: docker.io/fluxcapacitor/apachespark-worker-2.1.0:master
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 2000m
            memory: 2000Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_WORKER_CORES
          value: "2"
        - name: SPARK_WORKER_MEMORY
          value: 2g
        - name: SPARK_MASTER
          value: spark://apachespark-master-2-1-0:7077
        ports:
        - containerPort: 6061
